### ISSUE TITLE
Promise doesn't work

### ISSUE THREAD

**Issue by ilyamuromets** [LiquidPlayer/LiquidCore#36] opened 2017-09-04 15:43 UTC
I try to using Promise but nothing works out. The following code doesn't work:
```
var promise = new Promise(function(resolve, reject) {
    resolve(123);
});

promise.then(function(result) {
    console.log(result);
});
```
This code will work fine if I execute it in a browser.

**Comment by ilyamuromets** [comment] 2017-09-05 08:22
I checked the above code in **JSContext** without running **Microservice** - works fine!!
What could be the problem?

**Comment by ilyamuromets** [comment] 2017-09-06 07:14
I have found another interesting thing. If I kill process `process.exit(0);` then the promise function `resolve(123);` will be executed.

**Comment by ilyamuromets** [comment] 2017-09-07 07:44
I have found problem. When I start **Microservice** I eval the code `setInterval(function(){}, 3600000);`
When I changed code to `setInterval(function(){}, 1000);` pomises have worked.

**Comment by ericwlange** [comment] 2017-10-08 08:34
I find it shocking that `setInterval` would cause other events to block!  Let me see if that is the intended behavior.

**Comment by ericwlange** [comment] 2018-01-14 17:12
Not sure what the issue was before, but I added a test for this and it is passing with no trouble now.  Closing.

**Closed by ericwlange** 2018-01-14 17:12 UTC
