### ISSUE TITLE
EXC_BAD_ADDRESS supposedly on large strings

### ISSUE THREAD

**Issue by dsemenovsky** [LiquidPlayer/LiquidCore#145] opened 2019-12-19 02:21 UTC
I get this error when processing large data.
The same code works perfectly on Android.

<img width="1521" alt="Screen Shot 2019-12-18 at 9 17 40 PM" src="https://user-images.githubusercontent.com/367111/71139493-4b6a4980-21dc-11ea-9996-596b08368cf3.png">

**Comment by ericwlange** [comment] 2019-12-26 09:41
@dsemenovsky Thanks for reporting.  The issue is that I am allocating the temporary new string on the stack, and for large strings it blows the stack.  The solution is to allocate on the heap instead.  

For a quick fix, replace:
```c++
    char temp[length + 1];
```
with
```c++
    char *temp = (char*) malloc(length + 1);
```

and then after `JSStringRelease(s)`, put the following line:
```c++
    free(temp);
```

**Comment by dsemenovsky** [comment] 2019-12-26 15:48
@ericwlange Is the best way of doing it to fork the repo and install using Carthage from a fork after making these changes?

**Comment by ericwlange** [comment] 2020-01-07 19:30
accidental closure

**Comment by ericwlange** [comment] 2020-01-17 00:59
This is fixed in 0.7.x

**Closed by ericwlange** 2020-01-17 00:59 UTC
Labels: 0.7.0, ios
