### ISSUE TITLE
Crashes when running testJavaScriptCoreMiniDOM

### ISSUE THREAD

**Issue by mrueger42** [LiquidPlayer/LiquidCore#12] opened 2017-02-15 02:33 UTC
Device: Nexus 5X with 7.1.1
Emulator: Nexus 5 API 24

A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 19475 (roidJUnitRunner)

Build fingerprint: 'google/bullhead/bullhead:7.1.1/N4F26O/3582057:user/release-keys'
02-15 15:10:32.694 19491-19491/? A/DEBUG: Revision: 'rev_1.0'
02-15 15:10:32.694 19491-19491/? A/DEBUG: ABI: 'arm64'

**Comment by ericwlange** [comment] 2017-02-15 03:01
Thanks for registering the issue.  I am aware of this bug.  It should work fine if you run that test alone, but it will crash if you run it in sequence with the other JSC tests.

There is some disagreement between how I've implemented garbage collection and how JavaScriptCore expects it to happen.  This is occurring because the collector is running and clearing away unreferenced `JSValueRef`s, as the test code does not `JSValueRetain` the references.  (Note, these tests are not written by me -- these are Apple's JSC tests, so I treat them as the gold standard for expected behavior).  So there is some lifecycle assumption apparent in JSC that I haven't figured out yet.

I have slated this for fix in 0.3.0, which is the first release to actually use the JSC code (as it is required by React Native).  At the moment, the JSC functionality is experimental.

**Comment by mrueger42** [comment] 2017-02-15 03:15
There is a comment here
https://github.com/hszhsh/JavaScriptCore
relating to GC, not sure if that may be of any help
"I'm using WTF's RunLoop for GC timers on Android, so you need to call RunLoop::iterate() in your app's runloop on js thread."

**Comment by ericwlange** [comment] 2017-02-15 03:49
Well, I'm not actually using JSC at all.  LiquidCore runs on V8 -- I am shimming the JSC API and translating it to V8.  The tests are to ensure that it complies with what JSC applications expect.  I've cracked all other assumptions.  This is the one sinister bug that remains!

**Comment by ericwlange** [comment] 2017-03-25 11:38
Fixed in [345cc626d20005b3da063785dd99dcf21be33ebe](https://github.com/LiquidPlayer/LiquidCore/commit/345cc626d20005b3da063785dd99dcf21be33ebe)

**Comment by ericwlange** [comment] 2017-04-09 03:25
This is fixed in Release 0.2.2

**Closed by ericwlange** 2017-04-09 03:25 UTC
Labels: bug
